### PR TITLE
add displayAfterHiPayAccepted hook and allow to set special_cards in theme

### PR DESCRIPTION
**Pull request by pierrecle**
This pull request allows module consumer to override special_cards without overriding it in the module itself.
It also allows to perform some action with the accepted cart and order_id, with a hook "displayAfterHiPayAccepted".

### CODE REVIEW

**Comment by jprotin** [comment]
Hello !

Can you change your pull request from hipay:master to hipay:develop ?

Thank you very much for your contribution !

**Comment by pierrecle** [comment]
Done, with the add of more hooks: displayHiPayAccepted, displayHiPayCanceled, displayHiPayDeclined, displayHiPayException and displayHiPayPending.

**Comment by jprotin** [comment]
Hi Pierre,

You have created custom Hooks and added the procedure for installing and removing the module. 
Can you add the module update procedure? 
Using the directory "update" in the HiPay module, thus already having the module installed will automatically update with the custom hooks into database.

Does that sound possible and correct?

Thank you

All the best.

**Comment by pierrecle** [comment]
Hi Johan,

Sorry, I don't understand what do you expect, because I don't see any update directory in the module, and Prestashop uses install method on module update process.

Pierre.

**Comment by jprotin** [comment]
Sorry, i speaker about auto-update with directory "upgrade" but WE don't need it.

When we use a hook::exec, please prefer the syntax array() on input  that the syntax [ ]. The module must be compatible with old PHP. 

We can continous by email, if you want ? jprotin@hipay.com

Thx

**Pull request merged**
